# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:

   # Container registry service connection established during pipeline creation
   dockerRegistryServiceConnection: 'dcfcf908-3992-4499-9252-1648af30d467'
   imageRepository: 'cuongtruonghcmpipelinesjavascriptdocker'
   containerRegistry: 'mycontainerregistry20211215.azurecr.io'
   dockerfilePath: '**/Dockerfile'
   tag: '$(Build.BuildId)'
   imagePullSecret: 'mycontainerregistry202112157106fc5c-auth'

pool:
  name: Default
  demands:
   - agent.name -equals devops-agent  

stages:
 - stage: Build
   displayName: Build stage
   jobs:
   - job: Build
     displayName: Build
     steps:
     - task: Docker@2
       displayName: Build and push an image to container registry
       inputs:
         command: buildAndPush
         repository: $(imageRepository)
         dockerfile: $(dockerfilePath)
         containerRegistry: $(dockerRegistryServiceConnection)


     - publish: manifests
       artifact: manifests
