apiVersion : apps/v1
kind: Deployment
metadata:
  name: cuongtruonghcmpipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuongtruonghcmpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: cuongtruonghcmpipelinesjavascriptdocker 
    spec:
      containers:
        - name: cuongtruonghcmpipelinesjavascriptdocker 
          image: mycontainerregistry20211215.azurecr.io/cuongtruonghcmpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: __acr-secret__
